import { readFileSync, writeFileSync } from 'node:fs';
import { Command } from 'commander';
import { parseRubric } from '../review/rubric.js';
import {
  ciReviewRequestInputSchema,
  ciReviewRequestSchema,
  judgeCiReviewBatch,
  makeCiReviewRequest,
} from '../review/ci.js';
import { CheckFailure, invalidInputError } from '../util/errors.js';

/** Internal, file-only CLI for the P4-14 detached reviewer transport. */
export function registerCiReview(program: Command): void {
  const ci = program.command('ci-review').description('Internal detached CI reviewer transport');
  ci.command('prepare')
    .argument('<input>')
    .argument('<output>')
    .action((inputPath: string, outputPath: string) => {
      const raw = parseJson(inputPath, 'CI_REVIEW_INPUT');
      const input = ciReviewRequestInputSchema.safeParse(raw);
      if (!input.success)
        throw invalidInputError(
          'INVALID_CI_REVIEW_INPUT',
          input.error.message,
          'Fix the target-branch CI reviewer input.',
        );
      writeFileSync(outputPath, JSON.stringify(makeCiReviewRequest(input.data)) + '\n', 'utf8');
    });
  ci.command('judge')
    .argument('<request>')
    .argument('<batch>')
    .action((requestPath: string, batchPath: string) => {
      const raw = parseJson(requestPath, 'CI_REVIEW_REQUEST');
      const request = ciReviewRequestSchema.safeParse(raw);
      if (!request.success)
        throw invalidInputError(
          'INVALID_CI_REVIEW_REQUEST',
          request.error.message,
          'Fix the target-branch CI reviewer request.',
        );
      const rubric = parseRubric(request.data.rubric, `${requestPath}:rubric`);
      let text: string | undefined;
      try {
        text = readFileSync(batchPath, 'utf8');
      } catch {
        text = undefined;
      }
      const result = judgeCiReviewBatch({ text, request: request.data, rubric });
      process.stdout.write(JSON.stringify(result) + '\n');
      if (result.status === 'fail') throw new CheckFailure();
    });
}

function parseJson(path: string, code: string): unknown {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (cause) {
    throw invalidInputError(
      code,
      `${path}: could not parse JSON — ${cause instanceof Error ? cause.message : String(cause)}`,
      'Provide strict JSON generated by the target-branch reviewer workflow.',
    );
  }
}
