// `crucible init` — install a complete, working Crucible setup into a repo
// (charter §Configuration; design phase-2.md §7). init is the one command that
// WRITES the trusted-computing-base files a project is then governed by — the
// enforcement config, the schema bundles, the reviewer rubric, the role prompts,
// and the CI workflow — plus the convenience defaults and the managed agent
// block. Everything downstream (propose/approve/implement/verify) presupposes
// these files exist and validate; init is where they come from.
//
// Two properties are load-bearing:
//
//   1. It installs from SHIPPED SOURCES OF TRUTH, never hand-rolled strings:
//      the schema bundles come from `@crucible/schemas`, the CI workflow from
//      `@crucible/ci-templates`, the rubric + role prompts + convenience default
//      from `core/assets/`. `crucible doctor` (P2-13) later checks a project's
//      copies against these same sources — so init and doctor share one notion
//      of "the shipped version".
//
//   2. It NEVER silently overwrites (design §7 "re-run = diff-and-confirm"). A
//      fresh file is written; an identical file is left alone; a file that
//      exists with DIFFERENT bytes is only replaced if the caller confirms
//      (`confirmOverwrite`, the one injected decision edge — the CLI shows the
//      diff and reads y/N, tests script it). The gitignore + managed-block +
//      openspec-config surfaces are edited additively/in-region, so re-running
//      init on an already-initialized repo is a no-op that reports `unchanged`.
//
// The managed CLAUDE.md / AGENTS.md block is written with Crucible's OWN
// marker-delimited mechanism, replaced in place on re-run. (This intentionally
// does NOT use "OpenSpec's regeneration mechanism" the charter §267 aside names:
// the spike proved `openspec update` regenerates only `.claude/` integration
// files and never touches CLAUDE.md/AGENTS.md — see design phase-2.md §7. The
// design doc records this amendment.)
//
// Determinism (invariant 12): given the same repo state + `answers` + confirm
// decisions, init produces the same files and the same report. The interactive
// parts (adapter detection, the unit-test command, the y/N prompts) are resolved
// by the CLI into `answers` + `confirmOverwrite` before the core runs.

import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';
import { ciTemplatePathForAdapter } from '@crucible/ci-templates';
import { SCHEMA_BUNDLE_NAMES, schemaBundleDir } from '@crucible/schemas';
import {
  ADAPTER_LOCK_RELPATH,
  hashAdapterPackage,
  loadAdapterLock,
  serializeAdapterLock,
  type AdapterLock,
} from '../adapters/lockfile.js';
import { loadManifest } from '../adapters/manifest.js';
import {
  FRAMEWORK_PIN_RELPATH,
  serializeFrameworkPin,
  type FrameworkPin,
} from '../framework/pin.js';
import { invalidInputError } from '../util/errors.js';

import {
  MANAGED_SKILL_NAMES,
  renderManagedSkill,
  renderPinnedLauncher,
  validateManagedSkill,
} from '../session/skills.js';
// core/src/commands/init.ts (or core/dist/commands/init.js) → core/ → assets/,
// the same resolution `review/rubric.ts` uses for the shipped rubric default.
const assetsRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'assets');

/** The gitignore entries init guarantees (design §7): the personal convenience
 * layer and the two caller-minted, never-committed transcript/verdict trees. */
export const GITIGNORE_LINES = [
  '.crucible/local.yaml',
  '.crucible/transcripts/',
  '.crucible/verdicts/',
  '.crucible/sessions/',
  '.crucible/bin/',
] as const;

/** The files that carry Crucible's managed agent block (charter §267). */
export { MANAGED_SKILL_NAMES } from '../session/skills.js';
export const MANAGED_BLOCK_FILES = ['AGENTS.md', 'CLAUDE.md'] as const;

const MANAGED_BEGIN =
  '<!-- crucible:managed (generated by `crucible init` — do not edit inside) -->';
const MANAGED_END = '<!-- /crucible:managed -->';

/**
 * The resolved answers the CLI's interactive prompts (or `--yes` defaults)
 * produce, consumed by the deterministic core. `adapter`/`runners`/`paths` fill
 * `crucible.yaml`'s `adapters.<name>` block; `unitCommand` fills `suites.unit`
 * (charter §crucible.yaml Reference Shape: "the project's standard invocation,
 * recorded at init").
 */
export interface InitAnswers {
  adapter: string;
  runners: string[];
  paths: string[];
  unitCommand: string;
}

/** The one injected decision edge: overwrite a conflicting existing file?
 * Consulted ONLY when a target exists with different bytes (design §7's
 * diff-and-confirm) — fresh + identical files never ask. Async so the CLI can
 * render a diff and read y/N; tests pass a synchronous predicate. */
export type ConfirmOverwrite = (
  relpath: string,
  currentText: string,
  desiredText: string,
) => boolean | Promise<boolean>;

export interface InitDeps {
  confirmOverwrite: ConfirmOverwrite;
}

export interface AdapterPackageSource {
  manifestPath: string;
  executablePath: string;
}

export interface InitOptions {
  /** The repo root to install into. */
  root: string;
  /** The resolved install answers (adapter + unit command). */
  answers: InitAnswers;
  /** First-party package selected by the CLI detection edge, when shipped. */
  adapterPackage?: AdapterPackageSource;
  /** Validation-only pin for the framework source CI must build. */
  frameworkPin?: FrameworkPin;
}

/** What init did to one target path. `skipped` = a conflict the caller declined. */
export type InitActionKind = 'created' | 'updated' | 'unchanged' | 'skipped';
export interface InitAction {
  relpath: string;
  kind: InitActionKind;
}
export interface InitReport {
  actions: InitAction[];
}

/**
 * Install (or reconcile) a full Crucible setup under `options.root`. Returns a
 * file-by-file report of what changed. Never throws for an ordinary conflict —
 * a declined overwrite is a `skipped` action, not an error. (A genuinely
 * unreadable shipped asset would throw from the fs read, fail-closed: init
 * cannot install what it cannot read.)
 */
export async function init(options: InitOptions, deps: InitDeps): Promise<InitReport> {
  const { root, answers } = options;
  if (options.adapterPackage !== undefined) {
    const manifest = loadManifest(options.adapterPackage.manifestPath);
    if (manifest.name !== answers.adapter) {
      throw invalidInputError(
        'ADAPTER_PACKAGE_MISMATCH',
        `Detected adapter ${answers.adapter} does not match package ${manifest.name}.`,
        'Select the package whose manifest name matches the detected adapter.',
      );
    }
  }
  const actions: InitAction[] = [];
  const apply = (a: InitAction): void => {
    actions.push(a);
  };

  // 1. Enforcement config, rendered from the shipped reference shape + answers.
  await writeFullFile(root, 'crucible.yaml', renderCrucibleYaml(answers), deps, apply);

  // 1.5. Install + pin the detected first-party adapter package. The package
  // bytes and lockfile use init's existing diff-and-confirm edge on re-run.
  if (options.adapterPackage !== undefined) {
    await installAdapterPackage(root, options.adapterPackage, deps, apply);
  }

  // 1.75. Phase-4 validation bootstrap. Public package distribution remains
  // deferred; when the CLI has a source pin it records the exact framework
  // checkout CI must build. This file is consumed from the target branch by the
  // shipped workflow, never silently inferred in CI.
  if (options.frameworkPin !== undefined) {
    await writeFullFile(
      root,
      FRAMEWORK_PIN_RELPATH,
      serializeFrameworkPin(options.frameworkPin),
      deps,
      apply,
    );
  }

  // 2. Convenience defaults + reviewer rubric + role prompts (the .crucible TCB).
  await writeFullFile(
    root,
    join('.crucible', 'settings.yaml'),
    readAsset('settings.default.yaml'),
    deps,
    apply,
  );
  await writeFullFile(
    root,
    join('.crucible', 'rubric.yaml'),
    readAsset('rubric.default.yaml'),
    deps,
    apply,
  );
  for (const role of ['propose', 'implement', 'review'] as const) {
    await writeFullFile(
      root,
      join('.crucible', 'context', `${role}.md`),
      readAsset('context', `${role}.md`),
      deps,
      apply,
    );
  }

  // 3. Schema bundles — copied verbatim from @crucible/schemas (never generated;
  //    OpenSpec rejects the custom `oracles` artifact id — spike D5). Each bundle
  //    file lands under openspec/schemas/<name>/… and the change's `.openspec.yaml`
  //    pins the bundle at propose time (that pin IS the change type).
  for (const name of SCHEMA_BUNDLE_NAMES) {
    const bundleDir = schemaBundleDir(name);
    for (const rel of walkRelFiles(bundleDir)) {
      await writeFullFile(
        root,
        join('openspec', 'schemas', name, rel),
        readFileSync(join(bundleDir, rel), 'utf8'),
        deps,
        apply,
      );
    }
  }

  // 4. openspec/config.yaml — ensure `schema: crucible` (the community-schema
  //    path, spike-verified). Additive: an existing config keeps its other keys.
  await ensureOpenspecSchema(root, deps, apply);

  // 5. The CI workflow — the enforcement authority (invariant 7). Copied from
  //    @crucible/ci-templates into the conventional GitHub Actions location.
  await writeFullFile(
    root,
    join('.github', 'workflows', 'crucible.yml'),
    readFileSync(ciTemplatePathForAdapter(answers.adapter), 'utf8'),
    deps,
    apply,
  );

  // 6. The managed agent block — teach a conversational agent to DRIVE the CLI
  //    (charter §267). Marker-delimited, replaced in place on re-run.
  await ensureManagedBlock(root, 'AGENTS.md', managedBlock(), deps, apply);
  await ensureManagedBlock(root, 'CLAUDE.md', claudeBridgeBlock(), deps, apply);
  for (const name of MANAGED_SKILL_NAMES) {
    const skill = renderManagedSkill(name);
    validateManagedSkill(skill, name);
    for (const hostRoot of ['.agents', '.claude']) {
      await writeFullFile(root, join(hostRoot, 'skills', name, 'SKILL.md'), skill, deps, apply);
    }
  }
  if (options.frameworkPin !== undefined) {
    const frameworkRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
    await writeFullFile(
      root,
      join('.crucible', 'bin', 'crucible.mjs'),
      renderPinnedLauncher(options.frameworkPin, frameworkRoot),
      deps,
      apply,
    );
  }

  // 7. gitignore the personal layer + the caller-minted transcript/verdict trees.
  ensureGitignore(root, apply);

  return { actions };
}

async function installAdapterPackage(
  root: string,
  source: AdapterPackageSource,
  deps: InitDeps,
  apply: (action: InitAction) => void,
): Promise<void> {
  const sourceManifest = loadManifest(source.manifestPath);
  const manifestRel = `.crucible/adapters/${sourceManifest.name}.yaml`;
  const executableRel = `.crucible/adapters/${sourceManifest.name}.mjs`;

  await writeFullFile(root, manifestRel, readFileSync(source.manifestPath, 'utf8'), deps, apply);
  let executableAction: InitAction | undefined;
  await writeFullFile(
    root,
    executableRel,
    readFileSync(source.executablePath, 'utf8'),
    deps,
    (action) => {
      executableAction = action;
      apply(action);
    },
  );
  if (executableAction?.kind === 'created' || executableAction?.kind === 'updated') {
    chmodSync(join(root, executableRel), 0o755);
  }

  const installedManifest = loadManifest(join(root, manifestRel));
  const lockPath = join(root, ADAPTER_LOCK_RELPATH);
  const lock: AdapterLock = existsSync(lockPath)
    ? loadAdapterLock(lockPath)
    : { version: 1, adapters: {} };
  lock.adapters[installedManifest.name] = {
    version: installedManifest.version,
    manifest: manifestRel,
    executable: executableRel,
    content_hash: hashAdapterPackage(join(root, manifestRel), join(root, executableRel)),
  };
  await writeFullFile(root, ADAPTER_LOCK_RELPATH, serializeAdapterLock(lock), deps, apply);
}

/** Read a shipped asset from `core/assets/…` as UTF-8 (fail-closed if missing). */
function readAsset(...segments: string[]): string {
  return readFileSync(join(assetsRoot, ...segments), 'utf8');
}

/**
 * Write a full-content file with the diff-and-confirm contract: create when
 * absent, leave identical bytes alone, and replace differing bytes only if
 * `confirmOverwrite` says so (else `skipped`). This is the workhorse for every
 * whole-file install surface (config, rubric, prompts, schema files, workflow).
 */
async function writeFullFile(
  root: string,
  relpath: string,
  desired: string,
  deps: InitDeps,
  apply: (a: InitAction) => void,
): Promise<void> {
  const abs = join(root, relpath);
  if (!existsSync(abs)) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, desired, 'utf8');
    apply({ relpath, kind: 'created' });
    return;
  }
  const current = readFileSync(abs, 'utf8');
  if (current === desired) {
    apply({ relpath, kind: 'unchanged' });
    return;
  }
  if (await deps.confirmOverwrite(relpath, current, desired)) {
    writeFileSync(abs, desired, 'utf8');
    apply({ relpath, kind: 'updated' });
  } else {
    apply({ relpath, kind: 'skipped' });
  }
}

/**
 * Ensure `openspec/config.yaml` carries `schema: crucible` (design §7). Creates
 * the file when absent; on an existing file, preserves every other key and only
 * touches `schema` — and if `schema` already differs, that is a conflict routed
 * through `confirmOverwrite` (no silent overwrite of a human's config).
 */
async function ensureOpenspecSchema(
  root: string,
  deps: InitDeps,
  apply: (a: InitAction) => void,
): Promise<void> {
  const relpath = join('openspec', 'config.yaml');
  const abs = join(root, relpath);
  if (!existsSync(abs)) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, 'schema: crucible\n', 'utf8');
    apply({ relpath, kind: 'created' });
    return;
  }
  const current = readFileSync(abs, 'utf8');
  const parsed = (parseYaml(current) ?? {}) as Record<string, unknown>;
  if (parsed['schema'] === 'crucible') {
    apply({ relpath, kind: 'unchanged' });
    return;
  }
  // Set/replace the schema line while leaving the rest of the file byte-stable:
  // a targeted line edit reads more faithfully than a full YAML re-serialize.
  const desired = upsertYamlScalar(current, 'schema', 'crucible');
  if (await deps.confirmOverwrite(relpath, current, desired)) {
    writeFileSync(abs, desired, 'utf8');
    apply({ relpath, kind: 'updated' });
  } else {
    apply({ relpath, kind: 'skipped' });
  }
}

/**
 * Install/refresh the marker-delimited managed block in `file` (CLAUDE.md /
 * AGENTS.md). Absent file → created with just the block. Existing block →
 * replaced in place (idempotent: identical block → `unchanged`). Existing file
 * WITHOUT the block → the block is appended, and because that mutates a
 * human-authored file it goes through `confirmOverwrite` like any conflict.
 */
async function ensureManagedBlock(
  root: string,
  file: string,
  block: string,
  deps: InitDeps,
  apply: (a: InitAction) => void,
): Promise<void> {
  const abs = join(root, file);
  if (!existsSync(abs)) {
    writeFileSync(abs, block + '\n', 'utf8');
    apply({ relpath: file, kind: 'created' });
    return;
  }
  const current = readFileSync(abs, 'utf8');
  const begin = current.indexOf(MANAGED_BEGIN);
  if (begin !== -1) {
    const end = current.indexOf(MANAGED_END, begin);
    const endIdx = end === -1 ? current.length : end + MANAGED_END.length;
    const desired = current.slice(0, begin) + block + current.slice(endIdx);
    if (desired === current) {
      apply({ relpath: file, kind: 'unchanged' });
    } else if (await deps.confirmOverwrite(file, current, desired)) {
      writeFileSync(abs, desired, 'utf8');
      apply({ relpath: file, kind: 'updated' });
    } else {
      apply({ relpath: file, kind: 'skipped' });
    }
    return;
  }
  // No block yet: append it (separated by a blank line) — a real edit to a human
  // file, so confirm it.
  const desired = current.replace(/\s*$/, '') + '\n\n' + block + '\n';
  if (await deps.confirmOverwrite(file, current, desired)) {
    writeFileSync(abs, desired, 'utf8');
    apply({ relpath: file, kind: 'updated' });
  } else {
    apply({ relpath: file, kind: 'skipped' });
  }
}

/**
 * Ensure the `.gitignore` carries every `GITIGNORE_LINES` entry. Purely
 * ADDITIVE — existing lines are never rewritten or reordered, only missing
 * entries are appended — so this needs no confirm (it cannot clobber anything).
 * Absent file → created with the entries; all present → `unchanged`.
 */
function ensureGitignore(root: string, apply: (a: InitAction) => void): void {
  const relpath = '.gitignore';
  const abs = join(root, relpath);
  const header = '# Crucible — personal convenience + caller-minted trajectories (never committed)';
  if (!existsSync(abs)) {
    writeFileSync(abs, header + '\n' + GITIGNORE_LINES.join('\n') + '\n', 'utf8');
    apply({ relpath, kind: 'created' });
    return;
  }
  const current = readFileSync(abs, 'utf8');
  const present = new Set(current.split('\n').map((l) => l.trim()));
  const missing = GITIGNORE_LINES.filter((l) => !present.has(l));
  if (missing.length === 0) {
    apply({ relpath, kind: 'unchanged' });
    return;
  }
  const desired = current.replace(/\s*$/, '') + '\n' + header + '\n' + missing.join('\n') + '\n';
  writeFileSync(abs, desired, 'utf8');
  apply({ relpath, kind: 'updated' });
}

/** The managed agent block body (charter §267): drive the CLI, don't freelance. */
function managedBlock(): string {
  return [
    MANAGED_BEGIN,
    '## Crucible',
    '',
    'This repository is governed by **Crucible**: humans approve **artifacts** (specs +',
    'oracles), not code. Drive the CLI — do not freelance the workflow or edit gates.',
    '',
    '- Propose a change: `crucible propose <change> "<intent>"`',
    '- Approve it (a human seals the bundle): `crucible approve <change>`',
    '- Implement against the sealed oracles: `crucible implement <change>`',
    '- Check green/red: `crucible verify <change>`',
    "- Where am I, what's next: `crucible status <change>`",
    '',
    'Rules that bind you:',
    '',
    '- Never edit a sealed artifact or bound test after approval — the approval hash',
    '  voids on any change to sealed bytes.',
    '- `crucible.yaml`, the oracles, and everything under `.crucible/` are the trusted',
    '  computing base. CI judges by the **target branch**’s config, never the PR’s.',
    '- "Done" means the artifact validates or the named tests pass — never a self-report.',
    MANAGED_END,
  ].join('\n');
}

/** Claude Code compatibility bridge: canonical instructions live in AGENTS.md. */
function claudeBridgeBlock(): string {
  return [
    MANAGED_BEGIN,
    '## Crucible agent instructions',
    '',
    'Read and follow AGENTS.md before making any change. AGENTS.md is the canonical',
    'instruction file for this repository; this CLAUDE.md block is only a Claude Code bridge.',
    MANAGED_END,
  ].join('\n');
}

/**
 * Render `crucible.yaml` from the charter §Reference Shape with the answers'
 * adapter + unit command filled in. The risk globs are the shipped default set
 * (TCB paths + common critical surfaces); a project tightens them after init.
 */
function renderCrucibleYaml(answers: InitAnswers): string {
  const runners = answers.runners.map((r) => JSON.stringify(r)).join(', ');
  const paths = answers.paths.map((p) => JSON.stringify(p)).join(', ');
  return `# Crucible enforcement config (charter §Configuration & Reviewer Law).
# ENFORCEMENT ONLY: risk globs, tiers, adapters, suites, trajectory, audit.
# In CI this file is read from the *target* branch, never the PR branch
# (invariant 7). Convenience (models, notify) lives in .crucible/settings.yaml.
risk:
  critical: # any match → tier critical, human review required
    - "src/**/auth/**"
    - "src/**/payments/**"
    - "db/migrations/**"
    - "**/pom.xml" # dependency changes
    - "**/build.gradle*"
    - "AGENTS.md" # canonical agent instructions
    - "CLAUDE.md" # Claude compatibility bridge
    - ".agents/**" # shared agent skills and instructions
    - ".codex/**" # Codex project configuration
    - ".claude/**" # Claude Code project configuration
    - ".github/workflows/**" # CI is TCB
    - ".crucible/**" # harness is TCB (settings.yaml carved out below)
    - "openspec/schemas/**" # workflow definition is TCB
    - "crucible.yaml" # this file governs itself
  exempt:
    - ".crucible/settings.yaml"
    - ".crucible/local.yaml"

tiers:
  trivial: { diff_cap: 150 }
  standard: { diff_cap: 400 }
  critical: { diff_cap: 400, mutation: blocking }

adapters:
  ${answers.adapter}: { runners: [${runners}], paths: [${paths}] }

suites:
  unit: ${JSON.stringify(answers.unitCommand)} # the project's standard invocation

trajectory:
  require_local_verify: true
  iteration_budget: 12

audit:
  sample_rate: 0.1 # of auto-merges → weekly digest
`;
}

/**
 * Set-or-insert a top-level scalar `key: value` in a YAML document's TEXT,
 * preserving every other line. Replaces an existing top-level `key:` line;
 * otherwise prepends the pair. Deliberately text-level (not a re-serialize) so a
 * human's comments and ordering survive — init touches exactly the one key.
 */
function upsertYamlScalar(text: string, key: string, value: string): string {
  const line = `${key}: ${value}`;
  const re = new RegExp(`^${key}:.*$`, 'm');
  if (re.test(text)) return text.replace(re, line);
  const trimmed = text.replace(/^\s*\n/, '');
  return `${line}\n${trimmed}`;
}

/** Every file under `dir`, as paths relative to `dir` (for verbatim copying). */
function walkRelFiles(dir: string): string[] {
  const out: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current)) {
      const abs = join(current, entry);
      if (statSync(abs).isDirectory()) walk(abs);
      else out.push(relative(dir, abs));
    }
  };
  walk(dir);
  return out.sort();
}
