import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { init, type ConfirmOverwrite, type InitAnswers } from './init.js';

const ANSWERS: InitAnswers = {
  adapter: 'stub',
  runners: ['stub'],
  paths: ['**/*.ts'],
  unitCommand: 'npm test',
};

describe('init — agent instruction migration', () => {
  const roots: string[] = [];
  afterEach(() => {
    for (const root of roots) rmSync(root, { recursive: true, force: true });
    roots.length = 0;
  });

  it('replaces an old full CLAUDE managed block with the bridge and preserves human text', async () => {
    const root = mkdtempSync(join(tmpdir(), 'crucible-init-agent-migration-'));
    roots.push(root);
    writeFileSync(
      join(root, 'CLAUDE.md'),
      [
        '# Human Claude notes',
        '',
        '<!-- crucible:managed (generated by `crucible init` — do not edit inside) -->',
        '## Crucible',
        '',
        '- Propose a change: `crucible propose old "<intent>"`',
        '<!-- /crucible:managed -->',
        '',
        'Keep this footer.',
        '',
      ].join('\n'),
    );
    const confirm = vi.fn<ConfirmOverwrite>(() => true);

    const report = await init({ root, answers: ANSWERS }, { confirmOverwrite: confirm });

    const claude = readFileSync(join(root, 'CLAUDE.md'), 'utf8');
    expect(claude).toContain('# Human Claude notes');
    expect(claude).toContain('Keep this footer.');
    expect(claude).toContain('Read and follow AGENTS.md');
    expect(claude).not.toContain('crucible propose old');
    expect(report.actions.find((action) => action.relpath === 'CLAUDE.md')?.kind).toBe('updated');

    const agents = readFileSync(join(root, 'AGENTS.md'), 'utf8');
    expect(agents).toContain('crucible propose');
    expect(agents).not.toContain('only a Claude Code bridge');
  });
});
